### ISSUE TITLE
Running first test query fails :-(

### ISSUE THREAD

**Issue by gkowalski** [omoponfhir/omopv5_3_setup#1]
Running our first simple query : 

![image](https://user-images.githubusercontent.com/617805/176955620-966a5a1b-5ce5-4025-bfe9-e7d073fde88f.png)

THrows an exception : 

```
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: column "person_family_name" does not exist
  Position: 7445
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.runQuery(BaseEntityServiceImp.java:168)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.searchEntity(BaseEntityServiceImp.java:643)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.searchWithParams(BaseEntityServiceImp.java:1292)
	at edu.gatech.chai.omoponfhir.omopv5.r4.mapping.BaseOmopResource.searchWithParams(BaseOmopResource.java:180)
	at edu.gatech.chai.omoponfhir.omopv5.r4.provider.PatientResourceProvider$MyBundleProvider.getResources(PatientResourceProvider.java:524)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.createBundleFromBundleProvider(BaseResourceReturningMethodBinding.java:198)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:389)
	... 27 more
```

I don't see anywhere where the f_person table needs to have person_family_name in it ? 

Our table has : 

```
CREATE TABLE 
    f_person 
    ( 
        person_id          INTEGER NOT NULL, 
        family_name        CHARACTER VARYING(255), 
        given1_name        CHARACTER VARYING(255), 
        given2_name        CHARACTER VARYING(255), 
        prefix_name        CHARACTER VARYING(255), 
        suffix_name        CHARACTER VARYING(255), 
        preferred_language CHARACTER VARYING(255), 
        ssn                CHARACTER VARYING(12), 
        active             SMALLINT, 
        contact_point1     CHARACTER VARYING(255), 
        contact_point2     CHARACTER VARYING(255), 
        contact_point3     CHARACTER VARYING(255), 
        maritalstatus      CHARACTER VARYING(255) 
    );
```

**Comment by myungchoi** [comment]
Is f_person loaded for the person data?

**Comment by gkowalski** [comment]
Yes f_person is loaded with data . Is it referring to person.family_name ?

**Comment by myungchoi** [comment]
It is referring to f_person.family_name. Though the exception could be Ok. It could be person.family_name does not exist, which falls to the parent, which is f_person.family_name. The "_" is SELECT column alias. 

What repo are you using to run the omoponfhir4 server?

**Comment by gkowalski** [comment]
ok , I restarted the app and it started working

**Comment by gkowalski** [comment]
![image](https://user-images.githubusercontent.com/617805/176967449-1631c818-a531-4f45-aa1d-9ce3f62de1f4.png)


org.hl7.fhir.exceptions.FHIRException: Unknown V3MaritalStatus code 'MARRIED'
	at org.hl7.fhir.r4.model.codesystems.V3MaritalStatus.fromCode(V3MaritalStatus.java:109)

Complaining about the marital status  Gusss I should have looked at 

https://hapifhir.io/hapi-fhir/apidocs/hapi-fhir-structures-r4/org/hl7/fhir/r4/model/codesystems/V3MaritalStatus.html

for the values of this field first .

**Comment by myungchoi** [comment]
org.hl7.fhir.r4.model.codesystems.V3MaritalStatus is the package used for the marital status. So, the link seems to be right one. "unmarried" seems to be the one you want to use for "Single".
